### ISSUE TITLE
依赖安装正常但无法运行

### ISSUE THREAD

**Issue by lvjiawei1997** [Pzzzzz5142/Pbot#3]
nb run
Traceback (most recent call last):
  File "/usr/local/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/nb_cli/__init__.py", line 46, in run
    run_bot(file, app)
  File "/usr/local/lib/python3.8/site-packages/nb_cli/handlers.py", line 44, in run_bot
    module = importlib.import_module(module_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./bot.py", line 5, in <module>
    from Pbot.db import init_db
  File "./Pbot/db.py", line 1, in <module>
    from gino import Gino
ModuleNotFoundError: No module named 'gino'

**Comment by Pzzzzz5142** [comment]
（这里忘记加依赖了，本来认为db套件应该是可选的但是由于技术力不够pro导致必须安装数据库

先确保安装了 postgre 数据库

再 `poetry install -E db` 就可以了。（理论上是这样，不知道不配置数据库相关的内容是否可以运行，我没试过（（（（

目前是要删除 bot.py 里面的`pixiv_login()`

现在已经推送到github上了，重新pull一次就可以了。

**Comment by lvjiawei1997** [comment]
PostgreSQL 9.6.20 on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit
(1 row)

root@iZj6ci:~/Pbot#  poetry install -E db
Installing dependencies from lock file

Package operations: 2 installs, 0 updates, 0 removals

  • Installing asyncpg (0.21.0)
  • Installing gino (1.0.1)


root@iZj6cion0jekZ:~/Pbot# nb run
Traceback (most recent call last):
  File "/usr/local/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/nb_cli/__init__.py", line 46, in run
    run_bot(file, app)
  File "/usr/local/lib/python3.8/site-packages/nb_cli/handlers.py", line 44, in run_bot
    module = importlib.import_module(module_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./bot.py", line 5, in <module>
    from Pbot.db import init_db
  File "./Pbot/db.py", line 1, in <module>
    from gino import Gino
ModuleNotFoundError: No module named 'gino'

 
已经安装了postgre，但好像还是不行

**Comment by Pzzzzz5142** [comment]
怪事，能 `pip list` 一下吗？或者直接在终端输入 `python` 看看能不能 `import gino`

**Comment by lvjiawei1997** [comment]
Package                    Version
-------------------------- -------------
aiocache                   0.11.1
aiocqhttp                  1.2.5
aiofiles                   0.5.0
appdirs                    1.4.4
APScheduler                3.6.3
arrow                      0.17.0
binaryornot                0.4.4
blinker                    1.4
CacheControl               0.12.6
cachy                      0.3.0
certifi                    2020.12.5
cffi                       1.14.4
chardet                    3.0.4
cleo                       0.8.1
click                      7.1.2
clikit                     0.6.2
colorama                   0.4.4
cookiecutter               1.7.2
crashtest                  0.3.1
cryptography               3.3.1
cssselect                  1.1.0
distlib                    0.3.1
emoji                      0.5.4
fastapi                    0.63.0
feedparser                 6.0.2
filelock                   3.0.12
google-trans-new           1.1.9
googletrans                2.4.0
h11                        0.9.0
h2                         3.2.0
hpack                      3.0.0
hstspreload                2020.12.22
html5lib                   1.1
httpcore                   0.12.2
httptools                  0.1.1
httpx                      0.16.1
Hypercorn                  0.11.2
hyperframe                 5.2.0
idna                       2.8
itsdangerous               1.1.0
jeepney                    0.6.0
Jinja2                     2.11.2
jinja2-time                0.2.0
keyring                    21.8.0
lockfile                   0.12.2
loguru                     0.5.3
lxml                       4.6.2
MarkupSafe                 1.1.1
msgpack                    1.0.2
nb-cli                     0.3.2
nonebot-plugin-apscheduler 0.1.0
nonebot-plugin-songpicker2 0.1.2
nonebot-test               0.1.0
nonebot2                   2.0.0a8.post2
packaging                  20.8
pastel                     0.2.1
pexpect                    4.8.0
Pillow                     8.0.1
pip                        21.0.1
pkginfo                    1.7.0
poetry                     1.1.4
poetry-core                1.0.0
poyo                       0.5.0
priority                   1.3.0
prompt-toolkit             1.0.14
ptyprocess                 0.7.0
pycparser                  2.20
pydantic                   1.7.3
pyfiglet                   0.8.post1
Pygments                   2.7.4
pygtrie                    2.4.2
PyInquirer                 1.0.3
pylev                      1.3.0
pyparsing                  2.4.7
pyquery                    1.4.3
python-dateutil            2.8.1
python-dotenv              0.15.0
python-engineio            3.14.2
python-slugify             4.0.1
python-socketio            4.6.1
pytz                       2020.5
Quart                      0.11.5
regex                      2020.11.13
requests                   2.23.0
requests-toolbelt          0.9.1
retrying                   1.3.3
rfc3986                    1.4.0
SecretStorage              3.3.0
setuptools                 41.2.0
sgmllib3k                  1.0.0
shellingham                1.3.2
six                        1.15.0
sniffio                    1.2.0
starlette                  0.13.6
text-unidecode             1.3
toml                       0.10.2
tomlkit                    0.7.0
typing-extensions          3.7.4.3
tzlocal                    2.1
urllib3                    1.24.3
uvicorn                    0.11.8
uvloop                     0.14.0
virtualenv                 20.4.0
wcwidth                    0.2.5
webencodings               0.5.1
websockets                 8.1
Werkzeug                   1.0.1
wsproto                    1.0.0

**Comment by lvjiawei1997** [comment]
python
Python 3.8.0 (default, Dec  7 2020, 21:08:50) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by Pzzzzz5142** [comment]
看起来是因为你没有用poetry，所以安装出了点偏差。可以尝试直接pip安装gino和asyncpg。

**Comment by lvjiawei1997** [comment]
我一开始就用了poetry install了，pip也再走一遍了，

补了gino、asyncpg和aiohttp，现在是pixivpy3

nb run
Traceback (most recent call last):
  File "/usr/local/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/nb_cli/__init__.py", line 46, in run
    run_bot(file, app)
  File "/usr/local/lib/python3.8/site-packages/nb_cli/handlers.py", line 44, in run_bot
    module = importlib.import_module(module_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./bot.py", line 6, in <module>
    from Pbot.utils import init
  File "./Pbot/utils.py", line 6, in <module>
    from Pbot.pixiv import pixiv_api
  File "./Pbot/pixiv.py", line 1, in <module>
    from pixivpy3 import ByPassSniApi
ModuleNotFoundError: No module named 'pixivpy3'
root@iZj6cion0j2gl790ybvbekZ:~/Pbot# pip install pixivpy3
Looking in indexes: https://pypi.mirrors.ustc.edu.cn/simple/
ERROR: Could not find a version that satisfies the requirement pixivpy3
ERROR: No matching distribution found for pixivpy3

**Comment by lvjiawei1997** [comment]
poetry install
Installing dependencies from lock file

No dependencies to install or update

**Comment by Pzzzzz5142** [comment]
（（（（（（（（可能你用的是老版本的peotry lock file 安装的（（（（（（因为我用的nonebot版本是2.0.0a7而不是a8.post。

之前的那个file是有一点小问题的（（（（（（（（pixivpy3是当时我嫌peotry安装太慢了直接pip安装了（（（（（（

可能之后考虑解决这个问题（（（（（（（（（（（（

**Comment by Pzzzzz5142** [comment]
试试poetry nb run呢，因为poetry本身会创建一个虚拟环境，默认是不激活的。（突然想起来还有个issue没回复
